### PR TITLE
Added StuBistro Oettingerstrasse

### PR DESCRIPTION
**Pull request by JaWeilBaum**
We use this bot every day. Sadly it lacks the StuBistro Oettingerstraße, where we go to quiet often.

I'm not sure if I added everything what is needed, to add a new mensa - can't test locally.

### CODE REVIEW

**Comment by Alwinius** [comment]
Thanks for your contribution. There's indeed a small change needed in `mensa_notifications.py` to enable automatic updates in the background and keep the correct keyboard layout. @markuspi has just taken over development of this bot because I moved to Aachen. Therefore some bigger refactorings will take place soon.

**Comment by JaWeilBaum** [comment]
Thank you, I just added the necessary things to `mensa_notifications.py` 

So I guess its ready to be merged :)

**Comment by markuspi** [comment]
Thanks for your contribution. Even though I like the name Oettingerstraße, its real name is Oettinge**n**straße. Would be great if you could fix that.

**Comment by JaWeilBaum** [comment]
Yes you are right - probably to much Oettinger

**Review by markuspi — APPROVED** [review]
Looks good to me :+1:

**Comment by markuspi** [comment]
whoops, sorry

**Comment by Alwinius** [comment]
deployed

**Pull request merged**
